{{- if eq (default "" .Values.ldapAdmin.existingSecret.name) ""}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.ldapUserSecretName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- include "chart.selectorLabels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- /*
    retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
    and set $lldapUserPassword to existing secret data or generate a random one when not exists
  */}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "chart.ldapUserSecretName" .) ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $lldapUserPassword := (get $secretData "ldap_user_password") | default (randAlphaNum 32 | b64enc) }}
  username: {{ .Values.ldapAdmin.userName | b64enc }}
  password: {{ $lldapUserPassword }}
  email: {{ .Values.ldapAdmin.email | b64enc }}
{{- end}}
