{{- if and .Values.lldap.smtp.enablePasswordReset (eq (default "" .Values.lldap.smtp.user.existingSecret.name) "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lldap.smtpUserSecretName" . }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
    {{- include "lldap.selectorLabels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  username: {{ .Values.lldap.ldapUser.username | b64enc }}
  password: {{ .Values.lldap.ldapUser.password | b64enc }}
{{- end}}
